CREATE TABLE DMS_CUST_DOCUMENT(ID NUMBER(5),
					  NAME VARCHAR2(100),
					  DESCRIPTION VARCHAR2(200),
					  FPATH VARCHAR2(100),
					  CONTENT BLOB,
					  CUSTOMER_ID NUMBER(5),
					  PRIMARY KEY(ID));

CREATE SEQUENCE DMS_CUST_DOC_SEQ INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;
					  
CREATE TABLE DMS_CUSTOMER(ID NUMBER(5),
					  FIRST_NAME VARCHAR2(50),
					  LAST_NAME VARCHAR2(50),					  
					  PRIMARY KEY(ID));
					  
ALTER TABLE DMS_CUST_DOCUMENT ADD CONSTRAINT FK_CUST_DOC FOREIGN KEY(CUSTOMER_ID) REFERENCES DMS_CUSTOMER(ID);
					  
CREATE SEQUENCE DMS_CUST_SEQ INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;

CREATE TABLE DMS_USER_POST(ID NUMBER(5),TITLE VARCHAR2(100),DESCRIPTION VARCHAR2(200),CREATED_BY NUMBER(5),DOCUMENT_ID NUMBER(5),PRIMARY KEY(ID), FOREIGN KEY(DOCUMENT_ID) REFERENCES DOCUMENT(ID),FOREIGN KEY(CREATED_BY) REFERENCES DMS_USER(ID));

CREATE SEQUENCE DMS_USER_POST_SEQ INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;

CREATE TABLE DMS_USER_COMMENT(ID NUMBER(5),CONTENT VARCHAR2(200),CREATED_BY NUMBER(5),POST_ID NUMBER(5),PRIMARY KEY(ID),FOREIGN KEY(POST_ID) REFERENCES USER_POST(ID),FOREIGN KEY(CREATED_BY) REFERENCES DMS_USER(ID));
					  
CREATE SEQUENCE DMS_USER_COMMENT_SEQ INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;

CREATE TABLE DMS_USER(ID NUMBER(5),FIRST_NAME VARCHAR2(50),LAST_NAME VARCHAR2(50),PRIMARY KEY(ID));

CREATE SEQUENCE DMS_USER_SEQ INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;